name: taskpilot
description: A Flutter project for daily planning and productivity enhancement.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  fl_chart: ^0.60.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.0
  hive_generator: ^1.1.3

flutter:
  uses-material-design: true